quiz/app/urls.py
from django.urls import path
from app.views import index, quiz, top, quiz_multiple, upgrade


app_name = 'app'

urlpatterns = [
    path('', index, name='index'),
    path('quiz/', quiz, name='quiz'),
    path('quiz_multiple/', quiz_multiple, name='quiz_multiple'),
    path('top/', top, name='top'),
    path('upgrade/', upgrade, name='upgrade'),
]

quiz/quiz/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('', include('app.urls')),
]

quiz/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>   
  {% load static %} 
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
    <title>
      {% block title %}
              
      {% endblock %}
    </title>
  </head>

  <header>
    {% include 'includes/header.html' %}
  </header>

  <body>
    <main>
      <center>
      {% block content %}

      {% endblock %}
    </center>
    </main>

  </body>
</html>

quiz/templates/index.html
{%extends 'base.html'%}
{% block title %}
        Quiz
{% endblock %}

{% block content %}
  <div class="container py-5">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
         <b> Rules:</b><br>
          Answer questions, earn points to upgrade your status.
          <p>
            <div class="row justify-content-center"> 
              <div class="col-md-8 p-5"><p><b>Select Type of Questions: </b></p>
                <div class="card">
                 +1 point
                  <div class="card-header">
                    <i>The Python programming language gets its name from the British comedy group &quot;Monty Python.&quot;</i>
                  </div>
                  <a class="btn btn-primary btn-sm" href="{%url 'app:quiz'%}" role="button">True or False</a>
                </div>
              </div>
            </div>
          </p>
          <p>
            <div class="row justify-content-center"> 
              <div class="col-md-8 p-5">
                <div class="card">
                  +5 points
                  <div class="card-header ">
                    <i>Which programming language shares its name with an island in Indonesia?</i>
                    <div class="w-100 p-3" >
                      C++<br>
                      Java<br>
                      Python<br>
                      Jakarta<br>
                      
                  </div>
                  </div>
            <a class="btn btn-primary btn-sm" href="{%url 'app:quiz_multiple'%}" role="button">Multiple Choice</a>
          </div>
        </div>
      </div>
          </p>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

quiz/templates/quiz.html
{%extends 'base.html'%}
{%block content%}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Score: {{score.score}}
      </div>
      <div class="card-body">
        <p>
          <form method="post" action="{% url 'app:quiz' %}">
            {% csrf_token %}
            {%for result in results%}
              {{result.question|safe}} 
              <br><br>
              <input type="hidden" name="category" value="{{result.category}}">
              <input type="hidden" name="question" value="{{result.question}}">
              <div class="btn-group btn-group-toggle" data-toggle="buttons">
                <input class="btn btn-{%if correct_answer == 'True' %}success{%else%}secondary{%endif%}" type="{%if is_answered%}button{%else%}submit{%endif%}" name="user_answer" value="True"> 
                  <a class="btn btn-secondary" href="{%url 'app:quiz'%}" role="button">next</a>
                <input class="btn btn-{%if correct_answer == 'False' %}danger{%else%}secondary{%endif%}" type="{%if is_answered%}button{%else%}submit{%endif%}" name="user_answer" value="False"> 
              </div>
            {%endfor%}
          </form> 
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

quiz/templates/quiz_multiple.html
{%extends 'base.html'%}
{%block content%}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Score: {{score.score}}
      </div>
      <div class="card-body">
        <p>
          <form method="post" action="{% url 'app:quiz_multiple' %}">
            {% csrf_token %}
            {%for result in results%}
              <input type="hidden" name="question" value="{{result.question}}">
              {{result.question|safe}} 
            {%endfor%}
              <br><br>
              {%for answer in answers%}
                <p><input type="radio" class="button" required name="user_answer" value="{{answer}}">{{answer|safe}}</p>
              {%endfor%}
              {{correct_answer|safe}}<br>
              {%if is_post %}{%if is_answered %} <a class="btn btn-success" href="{%url 'app:quiz_multiple'%}" role="button">next</a> {%else%}<a class="btn btn-danger" href="{%url 'app:quiz_multiple'%}" role="button">next</a>{%endif%}{%else%} <input class="btn btn-secondary" type="submit"  value="Send">{%endif%}
            
          </form> 
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

quiz/templates/top.html
{%extends 'base.html'%}
{% block title %}
    Top
{% endblock %}
{%block content%}
<div class="container py-2">
  <table class="table table-striped">
    <thead>
      <tr >
        <th>nickname</th>
        <th>score</th>
      </tr>
    </thead>
    
    <tbody>
      {%for king in kings%}
        <tr >
          <td class="table-dark">{{king.user.username}} </td>
          <td class="table-dark">{{king.score}}</td>
        </tr>
      {%endfor%}
      {%for pro in pros%}
        <tr >
          <td class="table-danger">{{pro.user.username}} </td>
          <td class="table-danger">{{pro.score}}</td>
        </tr>
        {%endfor%}
      {%for amateur in amateurs%}
        <tr >
          <td class="table-success">{{amateur.user.username}} </td>
          <td class="table-success">{{amateur.score}}</td>
        </tr>
      {%endfor%}

    </tbody>
  </table>
</div>
{%endblock%}

quiz/templates/upgrade.html
{% extends 'base.html'%}
{%block title%}
Upgrade
{%endblock%}
{%block content%}

<div class="container py-5">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
            <div class="row justify-content-center"> 
                <div class="col-md-8 p-5"><p><b>{%if KING %}You are the KING!{%else%}Upgrade Your Status:{%endif%} </b>{{text|safe}}<br>
                  <div class="card">
                    Your score: {{score.score}}
                    <div class="card-header">
                        Your status: {{status}}<br>    
                    </div>
                  {% if upgrade%}
                    <form method="post" action="{% url 'app:upgrade' %}">
                      {% csrf_token %}
                    <input class="btn btn-success w-100" type="submit"  value="UPGRADE">
                  {%endif%}
                  </div>
                </div>
            </div>
        </div>
      </div>
    </div>
</div>

{%endblock%}