quiz/app/urls.py
from django.urls import path
from app.views import index, quiz, top, quiz_multiple, upgrade


app_name = 'app'

urlpatterns = [
    path('', index, name='index'),
    path('quiz/', quiz, name='quiz'),
    path('quiz_multiple/', quiz_multiple, name='quiz_multiple'),
    path('top/', top, name='top'),
    path('upgrade/', upgrade, name='upgrade'),
]

quiz/quiz/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('', include('app.urls')),
]

quiz/templates/includes/header.html
{% load static %} 
<nav class="navbar navbar-light" style="background-color:{%if status == 'Amateur'%} #20c997{%elif status == 'PRO'%} #dc3545{%elif status == 'KING'%} #adb5bd{%else%}lightskyblue{%endif%}">
 <div class="container">
   <a class="navbar-brand" href="{% url 'app:index' %}">
     <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
     <span style="color:red">Q</span>uiz
   </a>
   {% with request.resolver_match.view_name as view_name %}
   {% if user.is_authenticated %}
    <div class="bg text-dark">{{ user.username }}{% if view_name  == 'users:login' or view_name  == 'users:signup'  %}{%else%}:{{score.score}}{%endif%}</div>
   {%endif%}
   {% endwith %}
   {% with request.resolver_match.view_name as view_name %}

   <ul class="nav nav-pills">
    <li class="nav-item"> 
      <a class="nav-link link-light {% if view_name  == 'app:index' %}active{% endif %}" href="{% url 'app:index' %}">Home</a>
    </li>
    <ul class="nav nav-pills">
      <li class="nav-item"> 
        <a class="nav-link link-light {% if view_name  == 'app:upgrade' %}active{% endif %}" href="{% url 'app:upgrade' %}">Upgrade</a>
      </li>
   <ul class="nav nav-pills">
    <li class="nav-item"> 
      <a class="nav-link link-light {% if view_name  == 'app:top' %}active{% endif %}" href="{% url 'app:top' %}">Dashboard</a>
    </li>
     {% if user.is_authenticated %}
       <li class="nav-item"> 
         <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}" href="{% url 'users:logout' %}">Log out</a>
       </li>

     {% else %}
       <li class="nav-item"> 
         <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}" href="{% url 'users:login'%}">Log in</a>
       </li>
       <li class="nav-item"> 
         <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}" href="{% url 'users:signup'%}">Sign up</a>
       </li>
     {% endif %}
     {% endwith %}
   </ul>
 </div>
</nav> 